version: '3'

services:
  database:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=changeme
    networks:
      - external
    volumes:
      - ./bdd:/var/lib/mysql
    ports:
      - "3306:3306"
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:

  app:
    build:
      context: .
      dockerfile_inline: |
        FROM php:7.2-apache
        RUN docker-php-ext-install pdo pdo_mysql
        RUN docker-php-ext-enable pdo pdo_mysql
    volumes:
      - ./app/src:/var/www/html/
    ports:
      - "8000:80"
    networks:
      - external
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-pipeline-stages: |
          - regex:
              expression: '(level|lvl|severity)=(?P<level>\w+)'
          - labels:
              level:

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-web.rule=Host(`app.local`)"
      - "traefik.http.routers.app-web.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=80"


networks:
  external:
    external: true
